output.tf
https://tools.hmcts.net/jira/browse/RPE-1060
Adding name to output to be able to dependent for firewall changes.
```
[ ] Yes
[x] No
```
=> Adding name to output

main.tf
https://tools.hmcts.net/jira/browse/RDM-4236
```
[ ] Yes
[ ] No
```
=> Use key_vault_id instead of vault_uri

main.tf
idam-prod is also a valid name for prod environment
```
[ ] Yes
[X] No
```
=> BAU: Updating to include idam-prod

main.tf
=> TF 0.12.x compat

main.tf
https://tools.hmcts.net/jira/browse/SIDM-3898
allow for idam-prod2 
```
[ ] Yes
[x] No
```
=> SIDM-3898 - allow for idam-prod2 

set-postgres-permissions.bash
https://tools.hmcts.net/jira/browse/DTSPO-264
```
[ ] Yes
[ ] No
```
=> DTSPO-264 Fix directory for Jenkins log in

db-access.tf, db-read-access.tf, set-postgres-permissions.bash
https://tools.hmcts.net/jira/browse/DTSPO-264
Microsoft confirmed that SPs don't work for this functionality, only users.
```
[ ] Yes
[ ] No
```
=> DTSPO-264 Use user account instead of sp

README.md
https://tools.hmcts.net/jira/browse/DTSPO-266
=> DTSPO-266 Improve docs

README.md
https://tools.hmcts.net/jira/browse/DTSPO-266
Rendered version:
https://github.com/hmcts/cnp-module-postgres/blob/update-docs/README.md
=> DTSPO-266 Update database self service docs

README.md, db-read-access.tf, variables.tf
=> DTSPO-2880 Updated db-read access

README.md
=> Updating readme to reflect new bastion login workflow

db-access.tf, main.tf, output.tf, variables.tf
=> fix broken ad lookups

main.tf, private-endpoint.tf, provider.tf, variables.tf
https://tools.hmcts.net/jira/browse/DTSPO-4157
```
[ ] Yes
[ ] No
```
=> DTSPO-4157  adding tags to private endpoint

main.tf
https://tools.hmcts.net/jira/browse/DTSPO-4157
```
[ ] Yes
[ x] No
```
=> DTSPO-4157 modify azuread arguments

README.md, output.tf
As requested in [#76](https://github.com/hmcts/cnp-module-postgres/pull/76)
=> SIDM-6311 adding resource group to the output variables

README.md, variables.tf
remove default version in branch for postgres version
update readme
```
[ ] Yes
[ X ] No
```
=> remove default version

.gitignore, example/main.tf, main.tf, service-endpoint-support.tf, variables.tf
Format TF
Add in the local server name, so it is the correct format
Add in the subnet_filename that was missing
```
[ ] Yes
[ X ] No
```
=> Subnet filename update

README.md, main.tf, variables.tf
=> DTSPO-7246. Enable auto grow

README.md, example/main.tf, main.tf, variables.tf
Add second database to postgres server.
- for cft demo int work, wanting to add second database to same postgres server
- merging to master branch as fees&pay team use this, rather than private endpoint branch
```
[ ] Yes
[X] No
```
=> Add second database to postgres server

README.md, main.tf, variables.tf
add option for additional_databases
- some terraform fmt included
```
[ ] Yes
[X] No
```
=> add option for additional_databases

db-read-access.tf
add second null-resource set permissions for additional databases
```
[ ] Yes
[X] No
```
=> add second null-resource set permissions for additional databases
